### ISSUE TITLE
Invalid date

### ISSUE THREAD

**Issue by hansfpc** [lgaticaq/bip#111]
When I use psep.cl's endpoint (http://www.psep.cl/api/Bip.php?&numberBip=22261566), it returns the date, but when I try to ask for the same BIP! Card number using this lib, it show me "Invalid date"

Note: I was following the documentation (https://github.com/lgaticaq/bip#use)

![image](https://user-images.githubusercontent.com/12705403/39558670-fc2d6f7c-4e66-11e8-8dfc-a7a28b2e668d.png)

**Comment by lgaticaq** [comment]
Thanks, fix bug in v3.0.1

**Comment by hansfpc** [comment]
thanks a lot!
